apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1  # Always running single pod
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 034362057748.dkr.ecr.ap-south-1.amazonaws.com/consumer:latest
        imagePullPolicy: Always # Replace with your ECR URI
        env:
        # Redis configuration
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        # vLLM service URL
        - name: LLM_SERVICE_URL
          value: "http://vllm-service:8000"
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health checks
       