apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: 034362057748.dkr.ecr.ap-south-1.amazonaws.com/producer:latest
        imagePullPolicy: Always # Replace with your ECR URI
        ports:
        - containerPort: 8001
        env:
        # Redis configuration
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        # Producer port
        - name: PORT
          value: "8001"
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001