apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-storage
  labels:
    app: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi


# aws eks create-addon --cluster-name agentic-slip --addon-name aws-ebs-csi-driver
# aws eks describe-addon --cluster-name agentic-slip --addon-name aws-ebs-csi-driver
