apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer
        ports:
        - containerPort: 8001
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-host 
        - name: REDIS_PORT
          valueFrom:  
            configMapKeyRef:  
              name: redis-config  
              key: redis-port 
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        - name: REDIS_DB 
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-db
        - name: PORT
          value: "8001"



---

apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001